site:
  title: Aragon Docs
  url: https://docs.aragon.org
  start_page: ROOT::index.adoc
  keys:
    google_analytics: 'UA-85043059-1'
content:
  sources:
    - url: .
      branches: HEAD
      start_path: components/home
ui:
  bundle:
    url: ./ui/theme
asciidoc:
  attributes:
    idprefix: ''
urls:
  redirect_facility: netlify
