const sidebars = {
  osxSidebar: [{type: 'autogenerated', dirName: '.'}],
  advancedSidebar: [{type: 'autogenerated', dirName: '.'}],
  guidesSidebar: [{type: 'autogenerated', dirName: '.'}],
  supportSidebar: [{type: 'autogenerated', dirName: '.'}],
};

module.exports = sidebars;
