// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  osxSidebar: [{type: 'autogenerated', dirName: 'osx'}],
  sdkSidebar: [{type: 'autogenerated', dirName: 'sdk'}],
  subgraphSidebar: [{type: 'autogenerated', dirName: 'subgraph'}],
  ...require('./static/subgraph/sidebar-schema.js'),
};

module.exports = sidebars;
