const sidebars = {
  osxSidebar: [{type: 'autogenerated', dirName: 'overview'}],
  advancedSidebar: [{type: 'autogenerated', dirName: 'advanced'}],
  guidesSidebar: [{type: 'autogenerated', dirName: 'guides'}],
  supportSidebar: [{type: 'autogenerated', dirName: 'support'}],
};

module.exports = sidebars;
