
= Documentation

Aragon is a secure and modular tech stack for organizations to manage their protocols and assets onchain.

[.card-section]
== Guides
Aragon supports a diverse set of builders who want to build on top of OSx:

[.card-section.card-section-2col]

[.card.card-secondary.card-dao-guide]
--
xref:osx-contracts::guide-set-up-dao/index.adoc[[.card-title]#Building a DAO# [.card-body]#pass:q[Launch or upgrade your DAO directly by calling the OSx framework.]#]
--

[.card.card-secondary.card-plugin-guide]
--
xref:osx-contracts::guide-develop-plugin/index.adoc[[.card-title]#Developing a plugin# [.card-body]#pass:q[Create and publish  plugins to the Aragon Plugin Marketplace for others to use.]#]
--

[.card.card-secondary.card-building-app]
--
link:https://uikit.aragon.org/[[.card-title]#Building a custom application# [.card-body]#pass:q[Integrate OSx into custom web apps using our suite of React-based UI tools.]#]
--


== Aragon OSx

OSx is our Ethereum-based smart contract framework. It enables organizations to deploy custom governance tailored to their unique needs and securely adapt over time. It was designed to overcome the monolithic one-size-fits-approach commonly used by onchain organizations.

**In OSx everything is a permission.** Permissions are the core primitive that enables scalable governance in large and complex organizations.

== Aragon Plugins

Permissions can be granted to an OSx plugin address. Plugins contain governance logic inside of reusable contracts. Each plugin is limited in scope, with single-purpose logic that can be mixed and matched to compose novel governance designs.

Explore the link:https://github.com/aragon/osx-plugin-template-foundry[OSx Plugin Template] and publish your own, which can be used to extend any OSx-based organization with new governance logic.

== Governance Tooling

The link:https://uikit.aragon.org/[Governance UI Kit] and link:https://github.com/aragon/gov-app-template[Governance App Template] are used to build custom applications and UIs that integrate seamlessly with OSx.

== Questions?

We’re here to help you build your DAO, plugin, or own governance-based platform.

- Check out our *developer community* in link:https://discord.com/invite/aragonorg[our Discord]!
- **If you’re not a developer**, head over to our link:https://www.aragon.org/resource-library[Resource Library] to learn more about how to better govern your organization with Aragon.
