= Documentation

Explore our guides and examples to learn how. test  dsfasfasfzz

== The modular governance stack

Explanation here

=== Aragon OSx

Docs here

=== Plugin marketplace

Governance logic is encapsulated in reusable contracts called _plugins_.

Plugins are granted specific permissions depending what you want them to do. In practice, they often act as governing bodies or decision-making processes. For example, a token voting plugin or multisig plugin define all of their unique governance logic within the plugin itself. This “separation of concerns” keeps the protocol focused and ultimately more flexible.

The core plugins currently supported by Aragon are:
* *Token Voting*: Proposals are created for token holders and delegates to vote on proposals, with execution decided using a simple majority rule.
* *Multisig*: Proposals are created for designated addresses to approve, with execution decided by whether a minimum number of approvers is met.
* *Admin*: Proposals are created by designated addresses and immediately executed.
* *Staged Proposal Processor*: Proposals are created and progress through any number of stages, with other plugins either voting to approve or veto the proposal. The SPP plugin is essentially a cross-plugin state manager that enables governance processes with multiple stages and multiple governing bodies.

[.card-section]

== Governance Toolingz

Other description here.

[.card-section.card-section-2col]
====
[.card.card-primary.card-contracts]
--
xref:contracts::index.adoc[[.card-title]#Contracts# [.card-body]#pass:q[A library of modular, reusable, and secure smart contracts, written in Solidity.]#]
--

[.card.card-primary.card-defender]
--
xref:defender::index.adoc[[.card-title]#Defender# [.card-body]#pass:q[A mission-critical developer security platform to code, audit, deploy, monitor, and operate blockchain applications.]#]
--
====

[.card.card-secondary.card-upgrades]
--
xref:upgrades.adoc[[.card-title]#Upgrades# [.card-body]#pass:q[A comprehensive suite of contracts and tooling to deploy and manage upgradeable contracts on Ethereum.]#]
--

[.card.card-secondary.card-contracts-cairo]
--
xref:contracts-cairo::index.adoc[[.card-title]#Contracts for Cairo# [.card-body]#pass:q[A library for secure smart contract development written in Cairo for Starknet.]#]
--

[.card.card-secondary.card-contracts-stylus]
--
xref:contracts-stylus::index.adoc[[.card-title]#Contracts for Stylus# [.card-body]#pass:q[A library for secure smart contract development written in Rust for Arbitrum Stylus.]#]
--

[.card.card-secondary.card-substrate-runtimes]
--
xref:substrate-runtimes::index.adoc[[.card-title]#Substrate Runtimes# [.card-body]#pass:q[A collection of runtime templates for parachain development on Polkadot.]#]
--

[.card.card-secondary.card-solidity-docgen]
--
https://github.com/OpenZeppelin/solidity-docgen[[.card-title]#Solidity Docgen# [.card-body]#pass:q[A tool for automatically generating documentation based on the natspec comments of your Solidity contracts.]#]
--