= Governance Marketplace

The following plugins were built by third-party developers in the Aragon ecosystem or by members of the Aragon team.


WARNING: Plugins in the Governance Marketplace may not have gone through the same level of security review as official Aragon plugins. It is the responsibility of each DAO and its participants to evaluate each plugin prior to giving it any governance permissions. Use at your own risk. 


== Multichain token voting (with LayerZero)

link:https://github.com/aragon/toucan-voting-plugin[Toucan Voting Plugin]

link:https://github.com/aragon[@AragonR&D]

Leverages the LayerZero protocol for cross-chain messaging and the zkSync Era rollup for low-cost and secure voting. 

== Multichain token voting (with Hashi)

link:https://github.com/crosschain-alliance/toucan-voting-plugin/tree/feat/hashi[Toucan Voting Plugin]

link:https://github.com/allemanfredi[@allemanfredi]

A forked version of the Multichain token voting plugin that uses Hashi for cross-chain messaging.

== veGovernance

link:https://github.com/aragon/ve-governance[veGovernance]

link:https://github.com/aragon[@AragonR&D]

A modernized vote escrow (ve) and gauge-based governance model which can be used to foster a strong alignment between token holders and capital flows.

== Optimistic token voting

link:https://github.com/aragon/optimistic-token-voting-plugin[Optimistic token voting plugin]

link:https://github.com/aragon[@AragonR&D]

An optimistic voting plugin where selected groups or members can submit proposals and token holders can veto them.

== Polygon multithreshold multisig

link:https://github.com/aragon/polygon-multithreshold-multisig[Polygon multithreshold multisig]

link:https://github.com/aragon[@AragonR&D]

A multi-threshold approval mechanism for handling both standard and emergency proposals.
