= Governance Marketplace

The following plugins were built by third-party developers in the Aragon ecosystem or by members of the Aragon team.


WARNING: Plugins in the Governance Marketplace may not have gone through the same level of security review as official Aragon plugins. Use at your own risk.

== Plugins

=== https://github.com/aragon/toucan-voting-plugin[Multichain token voting (with LayerZero)]

By link:https://github.com/aragon[@AragonR&D]

Leverages the LayerZero protocol for cross-chain messaging and the zkSync Era rollup for low-cost and secure voting. 

=== https://github.com/crosschain-alliance/toucan-voting-plugin/tree/feat/hashi[Multichain token voting (with Hashi)]

link:https://github.com/allemanfredi[@allemanfredi]

A forked version of the Multichain token voting plugin that uses Hashi for cross-chain messaging.

=== https://github.com/aragon/ve-governance[veGovernance]

link:https://github.com/aragon[@AragonR&D]

A modernized vote escrow (ve) and gauge-based governance model which can be used to foster a strong alignment between token holders and capital flows.

=== https://github.com/aragon/optimistic-token-voting-plugin[Optimistic token voting]

link:https://github.com/aragon[@AragonR&D]

An optimistic voting plugin where selected groups or members can submit proposals and token holders can veto them.

=== https://github.com/aragon/polygon-multithreshold-multisig[Polygon multithreshold multisig]

link:https://github.com/aragon[@AragonR&D]

A multi-threshold approval mechanism for handling both standard and emergency proposals.

[.info-text-style]
_By installing and using these plugins, some of which are 3rd party plugins, you acknowledge that Aragon is not responsible for their functionality, security, updates, or any potential risks, including data loss or security breaches. Use of these plugins at your own risk, and you should verify their third-party privacy policies and terms before installation. Aragon disclaims all liability for any issues arising from the use of these plugins. Aragon disclaims all liability for any issues arising from the use of these plugins._