name: Deploy to GitHub Pages

on:
  push:
    branches:
      - feat/fleek-to-gh-page
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment environment'
        required: true
        default: 'staging'
        type: choice
        options:
          - staging
          - production

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: ${{ github.event.inputs.environment || 'production' }}
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'yarn'

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Build site (Production)
        if: ${{ github.event.inputs.environment == 'production' || github.event_name == 'push' }}
        run: |
          yarn build:master
          echo "ghdocs.aragon.org" > build/site/CNAME

      - name: Build site (Staging)
        if: ${{ github.event.inputs.environment == 'staging' }}
        run: |
          yarn build:staging
          echo "stg-ghdocs.aragon.org" > build/site/CNAME

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'build/site'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
